### ISSUE TITLE
Customizable PostgreSQL column names

### ISSUE THREAD

**Issue by niktheblak** [niktheblak/ruuvitag-gollector#34]
Currently ruuvitag-gollector expects a very certain PostgreSQL/TimescaleDB schema when it's doing inserts. However, not all users may want to use those column names or may find certain columns unnecessary.

Create a configuration item `[columns]` that allows the user to specify which columns they want and what their names are. For example,

```toml
[columns]
"time" = "ts"
"mac" = "mac"
"temperature" = "temperature"
"humidity" = "humidity"
"pressure" = "pressure"
"movement_counter" = "movementCounter"
"measurement_number" = "measurementNumber"
```
In this case the rest of the RuuviTag fields (e.g. acceleration) would not be sent at all.
